version: '3'
services:
  api-quality-backend-latest:
    image: apiaddicts/apitools-apigen-dotnet:latest
    build: .
    container_name: apigen-dotnet
#    image: api_quality_backend:dev
    ports:
      - 1000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
    networks:
      - networks_cloudappi
networks:
    networks_cloudappi:
        external: true